# Generated by Django 3.2.13 on 2022-06-05 18:49

import django.db.models.deletion
import tinymce.models
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description_short', models.CharField(max_length=300)),
                ('description_long', tinymce.models.HTMLField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
